sudo: required

language: java
jdk:
- openjdk8

services:
- docker

before_install:
- "docker pull levkuznetsov/rserve"
- "docker run -d -p 6311:6311 levkuznetsov/rserve"
- "docker ps -a"
- "netstat -ltpn"
- "env | grep DOCKER"

script:
- mvn verify
